completed mentors and cards styling
Codess-Cafe/Codess-Cafe-Website pull request #20
Opened 2021-09-12 10:05 UTC by navyasingla1309

I have made the following changes:
1. Stored mentor details in arrays in mentors page
2. rendered all elements of array through card
3. applied styling

2021-09-12 16:44 UTC, ShreyaPrasad1209 requested changes
@navyasingla1309 the changes are not responsive for iPhone 12. I have sent you the screencast on Discord as I was unable to share it here. Please make it responsive and check it using inspect element.

2021-09-12 16:45 UTC, navyasingla1309 commented
> @navyasingla1309 the changes are not responsive for iPhone 12. I have sent you the screencast on Discord as I was unable to share it here. Please make it responsive and check it using inspect element.

Ok I will correct it.

2021-09-12 17:44 UTC, ShreyaPrasad1209 requested changes

2021-09-12 17:44 UTC, ShreyaPrasad1209 commented on pages/mentors.js
> +    const mentors_r1 = [
Add "category" key in Mentors objects. Value can be anything from following:

- Competitive Programming
- Open Source
- Technical Interview Preparation

2021-09-12 17:44 UTC, ShreyaPrasad1209 commented on pages/mentors.js
> +    const mentors_r1 = [
Change mentors_r1 to Mentors

2021-09-12 18:20 UTC, navyasingla1309 commented on pages/mentors.js
> +    const mentors_r1 = [
Okay, will do it.

2021-09-13 05:20 UTC, ShreyaPrasad1209 approved these changes
Great work @navyasingla1309 🎉 I’ll merge this PR ✅

2021-09-13 05:21 UTC, merged